#!/usr/bin/env bash

if [ ${EUID} -ne 0 ]; then
  printf "apacheadm must be run as root!\n"
fi

APACHE_CONFIG_PATH="/etc/httpd/conf"

help() {
  printf "Usage:\n"
  printf "apacheadm enable-module [module]     Enable a module.\n"
  printf "apacheadm disable-module [module]    Disable a module.\n"
  printf "apacheadm enable-site [site]         Enable a site.\n"
  printf "apacheadm disable-site [site]        Disable a site.\n"
}

enable_module() {
  if [ -f ${APACHE_CONFIG_PATH}/mods-available/${1}.load ]; then
    if [ ! -e ${APACHE_CONFIG_PATH}/mods-enabled/${1}.load ]; then
      ln -s ${APACHE_CONFIG_PATH}/mods-available/${1}.* \
        ${APACHE_CONFIG_PATH}/mods-enabled/
      printf "Module ${1} enabled.\n"
    else
      printf "Module ${1} already enabled.\n"
    fi
  else
    printf "Module ${1} not available.\n"
  fi
}

disable_module() {
  if [ -e ${APACHE_CONFIG_PATH}/mods-enabled/${1}.load ]; then
    rm -f ${APACHE_CONFIG_PATH}/mods-enabled/${1}.{load,conf}
    printf "Module ${1} disabled.\n"
  else
    printf "Module ${1} not enabled.\n"
  fi
}

enable_site() {
  if [ -f ${APACHE_CONFIG_PATH}/sites-available/${1}.conf ]; then
    if [ ! -e ${APACHE_CONFIG_PATH}/sites-enabled/${1}.load ]; then
      ln -s ${APACHE_CONFIG_PATH}/sites-available/${1}.conf \
        ${APACHE_CONFIG_PATH}/sites-enabled/
      printf "Site ${1} enabled.\n"
    else
      printf "Site ${1} already enabled.\n"
    fi
  else
    printf "Site ${1} not available.\n"
  fi
}

disable_site() {
  if [ -e ${APACHE_CONFIG_PATH}/sites-enabled/${1}.conf ]; then
    rm -f ${APACHE_CONFIG_PATH}/sites-enabled/${1}.conf
    printf "Site ${1} disabled.\n"
  else
    printf "Site ${1} not enabled.\n"
  fi
}

case ${1} in
  "--help")         help;;
  "enable-module")  enable_module ${2};;
  "disable-module") disable_module ${2};;
  "enable-site")    enable_site ${2};;
  "disable-site")   disable_site ${2};;
esac

